name: MakeCode

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
        
  build:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: microbit pxt.json  
        uses: datamonsters/replace-action@master
        with:
          files: 'pxt.json'
          replacements: 'core=microbit' 
      - name: microbit compilation
        run: |
          npm install -g pxt
          pxt target microbit
          pxt install
          pxt build --cloud
        env:
          CI: true

      - name: maker pxt.json          
        uses: datamonsters/replace-action@master
        with:
          files: 'pxt.json'
          replacements: 'core=xinabox-cs11,test.ts=dummy.ts'
      - name: maker compilation
        run: |
          npm install -g pxt
          pxt target maker
          pxt install
          pxt build --cloud
        env:
          CI: true
